# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bdc9568ce84cf0080df5f2578c034015d5d5a89ecbc74c0a6d004a89b831ebd9234f87f66de5b8639593381df0fd0521553ed3edf5b4c2419a54097e9f7ed9c

test:
  secret_key_base: 51f15549740c59b0c30163d266ba3939124f5a4408fe54a22508d6455dafffc83adfceaa2fb33dd82cefdbd5388221d573bc2ce8878dfcc32ed69ea3b0cbb32b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
